CREATE TABLE payment_transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  transaction_key CHAR(64) NOT NULL UNIQUE,
  web_shield_id INT DEFAULT NULL,
  shield_name VARCHAR(100) DEFAULT NULL,
  shield_domain VARCHAR(255) DEFAULT NULL,
  manager_id INT DEFAULT NULL,
  manager_name VARCHAR(50) DEFAULT NULL,
  merchant_domain VARCHAR(255) NOT NULL,
  wc_order_id VARCHAR(100) DEFAULT NULL,
  wc_order_number VARCHAR(100) DEFAULT NULL,
  payment_provider VARCHAR(40) NOT NULL,
  provider_order_id VARCHAR(100) DEFAULT NULL,
  provider_transaction_id VARCHAR(100) DEFAULT NULL,
  payment_action VARCHAR(40) NOT NULL,
  status VARCHAR(40) NOT NULL,
  amount DECIMAL(18, 2) DEFAULT NULL,
  currency CHAR(3) DEFAULT NULL,
  provider_fee DECIMAL(18, 2) DEFAULT NULL,
  payout DECIMAL(18, 2) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  first_occurred_at DATETIME DEFAULT NULL,
  last_occurred_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_transactions_shield_date (web_shield_id, last_occurred_at),
  INDEX idx_transactions_manager_date (manager_id, last_occurred_at),
  INDEX idx_transactions_provider (payment_provider, provider_transaction_id),
  INDEX idx_transactions_status (status),
  INDEX idx_transactions_merchant (merchant_domain)
);

CREATE TABLE payment_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_key CHAR(64) NOT NULL UNIQUE,
  transaction_key CHAR(64) NOT NULL,
  web_shield_id INT DEFAULT NULL,
  shield_domain VARCHAR(255) DEFAULT NULL,
  manager_id INT DEFAULT NULL,
  manager_name VARCHAR(50) DEFAULT NULL,
  merchant_domain VARCHAR(255) NOT NULL,
  payment_provider VARCHAR(40) NOT NULL,
  payment_action VARCHAR(40) NOT NULL,
  status VARCHAR(40) NOT NULL,
  payload JSON DEFAULT NULL,
  occurred_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_events_transaction (transaction_key),
  INDEX idx_events_manager_date (manager_id, occurred_at),
  INDEX idx_events_provider (payment_provider, payment_action)
);
