const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const calls = [];
const peer = { postMessage: (payload, origin) => calls.push({ payload, origin }) };
const frame = { src: 'https://shield.example/checkout', contentWindow: peer };
const window = { location: { href: 'https://shop.example/' }, lazyStripeProtocol: { protocol: 'mecom' } };
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../assets/js/legacy-compat.js'), 'utf8'), { window, URL, WeakMap });
const compat = window.lazyStripeCompat;
assert.equal(compat.normalize({ source: {}, origin: 'https://shield.example', data: 'mecom-loadedPaymentFormStripe' }, [frame]), null);
assert.equal(compat.normalize({ source: peer, origin: 'https://evil.example', data: 'mecom-loadedPaymentFormStripe' }, [frame]), null);
assert.equal(compat.normalize({ source: peer, origin: 'https://shield.example', data: null }, [frame]), null);
const old = compat.normalize({ source: peer, origin: 'https://shield.example', data: 'mecom-loadedPaymentFormStripe' }, [frame]);
assert.equal(old.data, 'lazy-loadedPaymentFormStripe');
const payload = { name: 'lazy-submitFormStripe', value: { billing_details: { name: 'Test Buyer' } } };
compat.send(frame, payload);
assert.equal(calls.length, 1);
assert.equal(calls[0].payload.name, 'mecom-submitFormStripe');
assert.equal(calls[0].origin, 'https://shield.example');
assert.equal(payload.name, 'lazy-submitFormStripe');
const modern = compat.normalize({ source: peer, origin: 'https://shield.example', data: { name: 'lazy-paymentMethodIdStripe', value: 'pm_test' } }, [frame]);
assert.equal(modern.data.value, 'pm_test');
compat.send(frame, payload);
assert.equal(calls.length, 2);
assert.equal(calls[1].payload.name, 'lazy-submitFormStripe');
console.log('PASS: trusted iframe only, legacy/new messages, protocol negotiation, one command per send');
